### ISSUE TITLE
How to change output between speaker and headphones in iOS

### ISSUE THREAD

**Issue by wijesijp** [ryanheise/audio_session#46] opened 2021-11-02 06:22 UTC
I am having trouble figuring out how to change output in iOS

I thought following would change it . But it is giving me an error.
I am also seeing only the speaker option so I assume there must be a different way to do this.

await AVAudioSession().overrideOutputAudioPort(AVAudioSessionPortOverride.speaker);

Can anyone provide some assistance for this?

**Comment by ryanheise** [comment] 2021-11-02 07:28
I'll close this as a duplicate of #37 .
![Screen Shot 2021-11-02 at 6 23 18 pm](https://user-images.githubusercontent.com/19899190/139803428-c87753ea-847c-42cb-997b-3027633de5e2.png)

If anyone would like to discuss how this can be done, please discuss it in #37 and those discussions will also eventually lead to a convenience method.

**Closed by ryanheise** 2021-11-02 07:28 UTC
