### ISSUE TITLE
Feature Request: Add Output Modification Capability

### ISSUE THREAD

**Issue by Peng-Qian** [ryanheise/audio_session#95] opened 2023-05-25 02:28 UTC
Hey there,

Love the work you've done on this package. Quick suggestion - could we get a feature for changing outputs?

I've seen something similar in another package, along with its iOS and Android versions. Here are the links:

[Package Link](https://pub.dev/packages/flutter_audio_output)
[iOS Code Link](https://github.com/0x01-itsmurphy/flutter_audio_output/blob/main/ios/Classes/SwiftFlutterAudioOutputPlugin.swift)
[Android Code Link](https://github.com/0x01-itsmurphy/flutter_audio_output/blob/main/android/src/main/java/com/itsmurphy/flutter_audio_output/FlutterAudioOutputPlugin.java)

Could be a cool addition here.

**Comment by ryanheise** [comment] 2023-05-25 09:45
Would be happy to accept a pull request. I think all of the methods are already implemented in this package, so I assume you are just wanting a convenience method in the main `AudioSession` class.

**Comment by ryanheise** [comment] 2023-05-30 15:23
Duplicate of #39

**Comment by ryanheise** [comment] 2023-05-30 15:24
I'm closing as a duplicate of #39 and I'll copy your comment across to there.

**Closed by ryanheise** 2023-05-30 15:23 UTC

**Comment by Peng-Qian** [comment] 2023-05-31 10:11
Hi @ryanheise,

Thank you for extending the invitation. I've been quite tied up recently, but I have indeed managed to test and improve the aforementioned code. During the process, I also discovered that on iOS, the audio session possesses remarkable audio routing capabilities. It's noteworthy that this is the only package I've found that performs this task well.

I'd be more than happy to submit a pull request, which I'll likely get around to next week. However, it's worth mentioning that due to my non-native developer background, you may need to carry out some refactoring pertaining to the file structure and location.
