### ISSUE TITLE
setAllowedCapturePolicy() Not setting value

### ISSUE THREAD

**Issue by xuala69** [ryanheise/audio_session#58] opened 2022-05-17 10:43 UTC
AndroidAudioManager's setAllowedCapturePolicy() is not setting the value passed, below is my code and please let me know if I made a mistake or can do something to fix it. I want to set the AllowedCapturePolicy to allowNone( int value 3) .

`

Future<void> _setPolicy() async {
    try {
      await _manager
          .setAllowedCapturePolicy(AndroidAudioCapturePolicy.allowNone);
      final session = await AudioSession.instance;
      var _policy = await _manager.getAllowedCapturePolicy();
      log("getAllowedCapturePolicy $_policy");
    } catch (e) {
      log("Error : $e");
    }
  }

`

the log prints the value of the capture policy with index 1(allowAll) in the above code

**Comment by ryanheise** [comment] 2022-05-17 11:01
Thanks for reporting this. I can see there is a bug in the plugin trying to map the Android result to Dart enum values.

As a quick fix, you can try updating the following code in `lib/src/util.dart`:

```dart
T decodeMapEnum<T>(Map<int, T> values, int index, {int defaultIndex = 0}) =>
    values[index] ?? values[defaultIndex]!;
```

But I have another fix in mind which I'll commit later tonight.

**Comment by nessblo** [comment] 2022-05-17 22:02
Hi,
Help me please, i want the sound of my application to be recorded by another application, i used this function but it didn't work,

**Comment by ryanheise** [comment] 2022-05-18 01:59
I can't provide any advice on how to use Android APIs. In this issue we are testing the bug fix which I just committed so that the Android API result is returned correctly.

**Comment by xuala69** [comment] 2022-05-18 10:00
Just got a chance to test it out and works perfectly, thanks for the swift reply

**Comment by ryanheise** [comment] 2022-05-18 10:15
Hmm, when you say it doesn't work, do you mean that you're still getting back index 1? Are you able to see whether that's because it's defaulting to 1, or because the Android side is actually returning 1?

**Comment by nessblo** [comment] 2022-05-18 10:20
Hi, I test the patch and it perfectly works for me, I can retrieve the index wanted, however what advice can give me for the audio of my application is not registered by other applications.
 Thank you

**Comment by xuala69** [comment] 2022-05-18 10:40
I'm getting back the index that i set (i.e 3) now but the sounds are still captured by recording apps

**Comment by ryanheise** [comment] 2022-05-18 10:43
If that is the case, then audio_session is wrapping the Android behaviour exactly, and hence it's not a bug in this plugin but rather an issue with Android itself.

**Comment by xuala69** [comment] 2022-05-18 10:44
I see. thank you for the swift response

**Comment by ryanheise** [comment] 2022-05-27 09:01
I've now released this in 0.1.7 so I'll close the issue.

**Closed by ryanheise** 2022-05-27 09:01 UTC

**Comment by nessblo** [comment] 2022-10-20 14:56
> I'm getting back the index that i set (i.e 3) now but the sounds are still captured by recording apps

Hi, Have you solve this issue ?

**Comment by xuala69** [comment] 2022-10-20 16:16
Yes and no .... setting the policy is successful but that doesn't prevent audio recording in most brands as they have modified the Android OS to fit their needs. It blocks recording on pixel phones but not on other brands.

**Comment by nessblo** [comment] 2022-10-20 16:28
I have exactly the same problem, thanks for the answer.
