### ISSUE TITLE
[iOS] NSInvalidArgumentException (attempt to insert nil object from objects)

### ISSUE THREAD

**Issue by mehayhe** [ryanheise/audio_session#68] opened 2022-07-06 14:25 UTC
I'm seeing the following fatal exception in production on iOS. It happened in background mode but didn't crash the app though. Don't know how to reproduce it locally. Must be an edge case where certain data could be null. I think it's best to add null check or some error handling to prevent such exceptions.

Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x92d0c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  CoreFoundation                 0x18d6a8 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x197840 -[__NSPlaceholderDictionary initWithCapacity:].cold.1
4  CoreFoundation                 0x52338 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
5  CoreFoundation                 0x6f994 +[NSDictionary dictionaryWithObjects:forKeys:count:]
6  audio_session                  0x6de4 -[DarwinAudioSession encodePort:] + 282 (DarwinAudioSession.m:282)
7  audio_session                  0x6af4 -[DarwinAudioSession encodePortList:] + 272 (DarwinAudioSession.m:272)
8  audio_session                  0x87e4 -[DarwinAudioSession getCurrentRoute:result:] + 453 (DarwinAudioSession.m:453)
9  audio_session                  0x58e8 -[DarwinAudioSession handleMethodCall:result:] + 92 (DarwinAudioSession.m:92)
10 audio_session                  0x5208 __40-[DarwinAudioSession initWithRegistrar:]_block_invoke + 25 (DarwinAudioSession.m:25)
11 Flutter                        0x50d038 (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
12 Flutter                        0x41ce0 (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
13 Flutter                        0x3d3ca4 (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
14 Flutter                        0x2fbbf0 (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
15 Flutter                        0x2ff1bc (Missing UUID d24b4305a5d8348c8a0909c859505f3a)
16 CoreFoundation                 0xa7258 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
17 CoreFoundation                 0x30af8 __CFRunLoopDoTimer
18 CoreFoundation                 0x2b6b0 __CFRunLoopDoTimers
19 CoreFoundation                 0xb3a4 __CFRunLoopRun
20 CoreFoundation                 0x1e240 CFRunLoopRunSpecific
21 GraphicsServices               0x1988 GSEventRunModal
22 UIKitCore                      0x4e541c -[UIApplication _run]
23 UIKitCore                      0x27eb88 UIApplicationMain
24 Runner                         0x6538 main + 8 (AppDelegate.swift:8)
25 ???                            0x104e4c3d0 (Missing)
```

**Comment by ryanheise** [comment] 2022-07-06 15:19
Thanks for the report. I am not 100% sure, but if I am interpreting that stack trace correctly, the issue is in this method in `ios/Classes/DarwinAudioSession.m`:

```objc
- (NSNumber *)encodePortType:(AVAudioSessionPort)portType {
    if (!portType) return (id)[NSNull null];
    if (@available(iOS 14.0, *)) {
        NSDictionary *map = @{
            AVAudioSessionPortAVB: @(11),      
            AVAudioSessionPortDisplayPort: @(13),              
            AVAudioSessionPortFireWire: @(15),           
            AVAudioSessionPortPCI: @(16),      
            AVAudioSessionPortThunderbolt: @(17),              
            AVAudioSessionPortVirtual: @(19),          
        };
        if (map[portType]) return map[portType];
    }
    NSDictionary *map = @{
        AVAudioSessionPortBuiltInMic: @(0),              
        AVAudioSessionPortHeadsetMic: @(1),              
        AVAudioSessionPortLineIn: @(2),          
        AVAudioSessionPortAirPlay: @(3),           
        AVAudioSessionPortBluetoothA2DP: @(4),                 
        AVAudioSessionPortBluetoothLE: @(5),               
        AVAudioSessionPortBuiltInReceiver: @(6),                   
        AVAudioSessionPortBuiltInSpeaker: @(7),                  
        AVAudioSessionPortHDMI: @(8),        
        AVAudioSessionPortHeadphones: @(9),              
        AVAudioSessionPortLineOut: @(10),          
        AVAudioSessionPortBluetoothHFP: @(12),               
        AVAudioSessionPortCarAudio: @(14),           
        AVAudioSessionPortUSBAudio: @(18),           
    };
    return map[portType];
}
```

If `map` doesn't contain `portType`, then it will return `nil`. The above map was hardcoded with the then complete set of keys, but there is now a new one: `AVAudioSessionPortVirtual`. But since new keys can keep being added in new versions of iOS, it is bad to just return `map[portType]`, but to first check if it's `nil`.

If you're willing, you could test my theory on your own copy of `audio_session` by modifying that code and replacing the last line with:

```objc
return map[portType] ? map[portType] : (id)[NSNull null];
```

**Comment by mehayhe** [comment] 2022-07-07 02:42
I'm able to trigger the same fatal exception locally by updating the `encodePortType` method to this: 

```
- (NSNumber *)encodePortType:(AVAudioSessionPort)portType {
    if (!portType) return (id)[NSNull null];
    if (@available(iOS 14.0, *)) {
        NSDictionary *map = @{
//            AVAudioSessionPortAVB: @(11),
//            AVAudioSessionPortDisplayPort: @(13),
//            AVAudioSessionPortFireWire: @(15),
//            AVAudioSessionPortPCI: @(16),
//            AVAudioSessionPortThunderbolt: @(17),
//            AVAudioSessionPortVirtual: @(19),
        };
        if (map[portType]) return map[portType];
    }
    NSDictionary *map = @{
//        AVAudioSessionPortBuiltInMic: @(0),
//        AVAudioSessionPortHeadsetMic: @(1),
//        AVAudioSessionPortLineIn: @(2),
//        AVAudioSessionPortAirPlay: @(3),
//        AVAudioSessionPortBluetoothA2DP: @(4),
//        AVAudioSessionPortBluetoothLE: @(5),
//        AVAudioSessionPortBuiltInReceiver: @(6),
//        AVAudioSessionPortBuiltInSpeaker: @(7),
//        AVAudioSessionPortHDMI: @(8),
//        AVAudioSessionPortHeadphones: @(9),
//        AVAudioSessionPortLineOut: @(10),
//        AVAudioSessionPortBluetoothHFP: @(12),
//        AVAudioSessionPortCarAudio: @(14),
//        AVAudioSessionPortUSBAudio: @(18),
    };
    return map[portType];
}
```

I tried the code `return map[portType] ? map[portType] : (id)[NSNull null];` It did prevent the crash from `DarwinAudioPlugin.m` but there is now an exception from `darwin.dart` since the decoder is expecting portType to have a number.

```
2022-07-06 19:24:08.461447-0700 Runner[30625:11008448] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      AVAudioSessionPortDescription._fromMap (package:audio_session/src/darwin.dart:580:60)
#1      AVAudioSessionRouteDescription._fromMap.<anonymous closure> (package:audio_session/src/darwin.dart:531:57)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#3      ListIterable.toSet (dart:_internal/iterable.dart:218:18)
#4      AVAudioSessionRouteDescription._fromMap (package:audio_session/src/darwin.dart:533:14)
#5      AVAudioSession.currentRoute (package:audio_session/src/darwin.dart:193:43)
<asynchronous suspension>
#6      AudioSession.getDevices (package:audio_session/src/core.dart:308:28)
<asynchronous suspension>
#7      new AudioSession._.<anonymous closure> (package:audio_session/src/core.dart:62:29)
```

**Comment by ryanheise** [comment] 2022-07-07 02:57
Thanks for testing that. After checking the code again, I see it does actually define a mapping for `AVAudioSessionPortVirtual` but only on iOS 14 or later. So this error could be triggered on lower versions of iOS. Although that leaves the mystery of why the port type would be returning one of those iOS 14-specific enum values if a lower version of iOS is actually being used.

In any case, to make the code more robust, the Dart side needs to either change the type of this enum to be nullable, or else give it a default value. Changing the nullability is a breaking change, but I also can't see what might be an appropriate default value.

Or, perhaps I can define my own mirror of the complete set of enum values on the platform side so that it doesn't trigger any minimum iOS constraint during the build.

**Comment by ryanheise** [comment] 2022-07-07 02:59
As far as defaults are concerned, maybe `AVAudioSessionPortVirtual` is a reasonable default if the actual port type can't be identified.

**Comment by ryanheise** [comment] 2022-07-07 03:19
Actually, the code is already using a default, but there is just a bug in that default fallback code.

I've just pushed a fix to `master` to this and also including the previously mentioned fix to the platform code. Let me know if that solves the error for you, although keep in mind that the default value for the port type might not be satisfactory for you. If you're getting a default value but you need to know the actual value, I'll need to do some more work involving mirroring the enum values.

**Comment by mehayhe** [comment] 2022-07-07 13:35
The exception from production was from an iOS 15 device. 

The fix looks good to me. I don't need to access the port type directly so it doesn't matter what value it is.

**Comment by ryanheise** [comment] 2022-07-07 15:33
Great! I have now published the fix on pub.dev (version 0.1.9) so I'll close.

**Closed by ryanheise** 2022-07-07 15:33 UTC
